### PR TITLE
add Control Plane (cpln) repo & owners

### PR DESCRIPTION
**Pull request by vavsab**
Set owners for https://github.com/pulumiverse/pulumi-cpln

### CODE REVIEW

**Comment by ringods** [comment]
@rebelopsio an existing repository was transferred as part of this setup, which means we need to import the existing setup into Pulumi state. Ping me when you have time and I'll sketch you through the process.

**Comment by rebelopsio** [comment]
@ringods I will reach out tomorrow morning for the import.

**Comment by ringods** [comment]
@vavsab I'm going to pick this up with @rebelopsio on Thu 7 Mar.

**Comment by vavsab** [comment]
🥹🙏

**Comment by ringods** [comment]
@vavsab quick request: can you add the line `import: true` to the repository yaml file?

Examples: #163

**Comment by vavsab** [comment]
@ringods done!

**Comment by rebelopsio** [comment]
@ringods please take a look at changes to ts files here to accommodate the deprecated GitHub setting that was preventing import. To prevent any sort of sync issues, I have added them to this PR. I can move them out if we think it makes sense.

**Comment by ringods** [comment]
@rebelopsio can you undo all the indentation changes? This is very hard to see what you actually changed to the code.

**Comment by rebelopsio** [comment]
@ringods apologies! Give me a few. Auto format strikes again.

**Review by ringods — APPROVED** [review]

**Pull request merged**
