### PR TITLE
docs: Adding a README documenting the current infrastructure in use.

### PR DESCRIPTION
**Pull request by ringods**
I added to the README every infrastructure aspect I can remember which is in use for Pulumiverse.

Signed-off-by: Ringo De Smet <ringo@de-smet.name>

### CODE REVIEW

**Review by cobraz — APPROVED** [review]
We should probably add ImproxMX also (our email alias service), but that shouldn't block this from being landed. Great work, thanks!

**Comment by ringods** [comment]
@cobraz good catch. Can you make an issue for that so we don't forget it once this PR is merged?

**Comment by tenwit** [comment]
LGTM

**Review by tenwit — APPROVED** [review]
LGTM

**Pull request merged**
